### ISSUE TITLE
variable no longer supported, please upgrade your application

### ISSUE THREAD

**Issue by mzeidhassan** [SemanticSoftwareLab/TextMining-MuNPEx#1]
Hi @baharsateli and @rene-w ,

I am trying to Use MuNPEx with the latest stable release of GATE, but it doesn't seem to work. Here is the error I am getting. Can you please let me know how can I fix this issue?

`GATE 8.6-SNAPSHOT build 5dbfc4b started at Sat Oct 06 15:31:25 MDT 2018
and using Java 1.8.0_181 Oracle Corporation on Linux amd64 4.4.0-136-generic.
gate.util.GateRuntimeException: $gatehome$ variable no longer supported, please upgrade your application
gate.persist.PersistenceException: gate.util.GateRuntimeException: $gatehome$ variable no longer supported, please upgrade your application
	at gate.util.persistence.PersistenceManager.loadObjectFromUri(PersistenceManager.java:1290)
	at gate.gui.MainFrame$LoadResourceFromFileAction$1.run(MainFrame.java:3691)
	at java.lang.Thread.run(Thread.java:748)
Caused by: gate.util.GateRuntimeException: $gatehome$ variable no longer supported, please upgrade your application
	at gate.util.persistence.PersistenceManager$URLHolder.unpackPersistentRepresentation(PersistenceManager.java:486)
	at gate.util.persistence.PersistenceManager$URLHolder.createObject(PersistenceManager.java:458)
	at gate.util.persistence.PersistenceManager.getTransientRepresentation(PersistenceManager.java:820)
	at gate.util.persistence.CollectionPersistence.createObject(CollectionPersistence.java:82)
	at gate.util.persistence.PersistenceManager.getTransientRepresentation(PersistenceManager.java:820)
	at gate.util.persistence.PersistenceManager.getTransientRepresentation(PersistenceManager.java:801)
	at gate.util.persistence.PersistenceManager.loadObjectFromUri(PersistenceManager.java:1243)
	... 2 more
  Caused by:
gate.util.GateRuntimeException: $gatehome$ variable no longer supported, please upgrade your application
	at gate.util.persistence.PersistenceManager$URLHolder.unpackPersistentRepresentation(PersistenceManager.java:486)
	at gate.util.persistence.PersistenceManager$URLHolder.createObject(PersistenceManager.java:458)
	at gate.util.persistence.PersistenceManager.getTransientRepresentation(PersistenceManager.java:820)
	at gate.util.persistence.CollectionPersistence.createObject(CollectionPersistence.java:82)
	at gate.util.persistence.PersistenceManager.getTransientRepresentation(PersistenceManager.java:820)
	at gate.util.persistence.PersistenceManager.getTransientRepresentation(PersistenceManager.java:801)
	at gate.util.persistence.PersistenceManager.loadObjectFromUri(PersistenceManager.java:1243)
	at gate.gui.MainFrame$LoadResourceFromFileAction$1.run(MainFrame.java:3691)
	at java.lang.Thread.run(Thread.java:748)
CREOLE plugin loaded: Learning Framework`

Thanks,
Mohamed

**Comment by mzeidhassan** [comment]
One more thing:
I couldn't find it under CREOLE manager, so I downloaded your package and installed it manually.
